### PR TITLE
Add empty verify pipeline

### PR DESCRIPTION
**Pull request by skeshari12**
Signed-off-by: skeshari12 <skeshari@msystechnologies.com>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by jayashrig158 — APPROVED** [review]

**Comment by tas50** [comment]
This is already done here https://github.com/chef/corefoundation/blob/main/.github/workflows/unit.yml#L16

**Review by rishichawda — COMMENTED** [review]
I'm unsure what this PR is trying to achieve since there is no description. But if the motivation is to have tests run in a pipeline that is public, we already do that for ruby 2.7, 3.0 and 3.1 through GitHub workflows. Is there any other reason? @skeshari12

**Comment by skeshari12** [comment]
> 
Hi Rishi, we want to run test on ruby 2.7, 3.0 and 3.1 using the PR verify pipeline As we are doing it for all the other managed repositories.

**Comment by skeshari12** [comment]
This is already done here https://github.com/chef/corefoundation/blob/main/.github/workflows/unit.yml#L16

**Pull request closed without merging**
